#!/usr/bin/env python3
"""Render the effective resolved SMA-NG configuration.

Resolves the four-bucket sma-ng.yml (daemon / base / profiles / services)
into the *effective* base block that the daemon would use after the named
profile's overlay is applied — equivalent to ``ConfigLoader.apply_profile``
which the runtime calls per job. Useful for answering "what would actually
happen if a file hit profile `rq`?" without reading the daemon's logs.

Usage::

    mise run config:show                     # raw base, no profile applied
    mise run config:show -- --profile rq     # base + rq profile overlay
    mise run config:show -- --profile rq --section video
    mise run config:show -- --profile rq --format json
    mise run config:show -- --profile rq --diff   # only fields the profile changes
    mise run config:show -- --config /opt/sma/config/sma-ng.yml --profile hq

When ``--diff`` is set, only fields where the profile overlay differs from
the base block are shown (skipping every field that passed through
unchanged). Useful for confirming a profile carries only the deltas you
expect.
"""

from __future__ import annotations

import argparse
import copy
import json
import logging
import sys
from pathlib import Path
from typing import Any

# Allow running as a script from anywhere — pretend we're at repo root.
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
  sys.path.insert(0, str(ROOT))

import yaml  # noqa: E402

from resources.config_loader import ConfigError, ConfigLoader  # noqa: E402
from resources.config_schema import SmaConfig  # noqa: E402


def _default_source() -> tuple[str, str]:
  """Pick the most operator-useful default config source.

  Returns ``(path, label)`` where ``label`` is a short human-readable
  description. Search order:

  1. ``config/sma-ng.yml`` — present only when the daemon runs locally
     (rare during development).
  2. ``.deploy-staging/<host>/config/sma-ng.yml`` — generated by the
     most recent ``mise run deploy:config`` run. Shows exactly what
     would land on the host.
  3. ``synthesize`` — special sentinel meaning "build the four-bucket
     dict in-memory by deep-merging ``setup/local.yml`` onto
     ``setup/sma-ng.yml.sample``". Useful before a first deploy.
  """
  candidates = [
    (ROOT / "config" / "sma-ng.yml", "config/sma-ng.yml"),
  ]
  staging = ROOT / ".deploy-staging"
  if staging.is_dir():
    for host_dir in sorted(staging.iterdir()):
      candidate = host_dir / "config" / "sma-ng.yml"
      if candidate.is_file():
        candidates.append((candidate, f".deploy-staging/{host_dir.name}/config/sma-ng.yml"))
        break
  for path, label in candidates:
    if path.is_file():
      return str(path), label
  return "synthesize", "synthesized from setup/local.yml + setup/sma-ng.yml.sample"


def _deep_merge(dst: dict[str, Any], src: dict[str, Any]) -> dict[str, Any]:
  """Recursive merge: dicts merge, everything else in src overwrites dst."""
  for key, value in src.items():
    if isinstance(value, dict) and isinstance(dst.get(key), dict):
      _deep_merge(dst[key], value)
    else:
      dst[key] = value
  return dst


def _synthesize_config() -> dict[str, Any]:
  """Build the four-bucket sma-ng.yml dict by merging local.yml onto sample.

  Mirrors what ``stamp_daemon.py`` does at deploy time, minus credential
  stamping (which only matters when pushing to a host). The result is a
  dict ready to feed to ``SmaConfig.model_validate``.
  """
  sample = ROOT / "setup" / "sma-ng.yml.sample"
  local = ROOT / "setup" / "local.yml"
  if not sample.is_file():
    sys.stderr.write(f"error: missing schema sample: {sample}\n")
    sys.exit(1)
  with open(sample) as f:
    merged = yaml.safe_load(f) or {}
  if local.is_file():
    with open(local) as f:
      local_data = yaml.safe_load(f) or {}
    for bucket in ("daemon", "base", "profiles", "services"):
      block = local_data.get(bucket)
      if isinstance(block, dict):
        merged.setdefault(bucket, {})
        _deep_merge(merged[bucket], copy.deepcopy(block))
  return merged


def _parse_args() -> argparse.Namespace:
  p = argparse.ArgumentParser(
    description="Render the effective SMA-NG config for a given profile.",
  )
  p.add_argument(
    "--config",
    "-c",
    default=None,
    help="Path to sma-ng.yml (default: auto-detect from config/, .deploy-staging/, or synthesize from setup/local.yml + setup/sma-ng.yml.sample).",
  )
  p.add_argument(
    "--profile",
    "-p",
    default=None,
    help="Named profile to overlay onto base. Omit for the raw base block.",
  )
  p.add_argument(
    "--section",
    "-s",
    default=None,
    help="Narrow output to one base section (e.g. 'video', 'hdr', 'audio').",
  )
  p.add_argument(
    "--format",
    "-f",
    choices=("yaml", "json"),
    default="yaml",
    help="Output format (default: yaml).",
  )
  p.add_argument(
    "--diff",
    action="store_true",
    help="With --profile, show only the fields the profile overlay changes relative to the raw base block. Useful for confirming a profile carries only deltas.",
  )
  p.add_argument(
    "--input",
    "-i",
    default=None,
    help="Path to a real media file. Probes the file, runs generateOptions, and prints the full FFmpeg command that would be executed under the chosen profile — without actually transcoding. Pairs naturally with --profile.",
  )
  return p.parse_args()


def _load(config_path: str) -> SmaConfig:
  if config_path == "synthesize":
    try:
      raw = _synthesize_config()
      return SmaConfig.model_validate(raw)
    except Exception as exc:
      sys.stderr.write(f"error synthesizing config: {exc}\n")
      sys.exit(1)
  path = Path(config_path)
  if not path.is_file():
    sys.stderr.write(f"error: config not found: {config_path}\n")
    sys.exit(1)
  loader = ConfigLoader(logger=logging.getLogger("show-config"))
  try:
    return loader.load(str(path))
  except ConfigError as exc:
    sys.stderr.write(f"error: {exc}\n")
    sys.exit(1)


def _resolve(cfg: SmaConfig, profile: str | None) -> dict[str, Any]:
  """Return the resolved base block as a kebab-cased dict.

  Uses ``mode="json"`` so enum fields (``FallbackPolicy``) serialise to
  their string values rather than the native Python enum object — PyYAML
  can't represent the latter and would raise ``RepresenterError``.
  """
  loader = ConfigLoader(logger=logging.getLogger("show-config"))
  base = loader.apply_profile(cfg, profile)
  return base.model_dump(by_alias=True, exclude_none=False, mode="json")


def _diff(base: dict[str, Any], resolved: dict[str, Any]) -> dict[str, Any]:
  """Recursive deep-diff: keep keys where ``resolved`` differs from ``base``.

  Dicts recurse; lists and scalars are compared by value. Keys absent from
  one side appear with their present value.
  """
  out: dict[str, Any] = {}
  all_keys = set(base) | set(resolved)
  for key in all_keys:
    bv = base.get(key)
    rv = resolved.get(key)
    if isinstance(bv, dict) and isinstance(rv, dict):
      sub = _diff(bv, rv)
      if sub:
        out[key] = sub
    elif bv != rv:
      out[key] = rv
  return out


def _filter_section(data: dict[str, Any], section: str | None) -> Any:
  if section is None:
    return data
  if section not in data:
    sys.stderr.write(f"error: no such section '{section}' (available: {sorted(data)})\n")
    sys.exit(1)
  return {section: data[section]}


def _emit(data: Any, fmt: str) -> None:
  if fmt == "json":
    json.dump(data, sys.stdout, indent=2, sort_keys=False, default=str)
    sys.stdout.write("\n")
  else:
    yaml.safe_dump(data, sys.stdout, sort_keys=False, default_flow_style=False)


def _render_ffmpeg_preview(input_path: str, profile: str | None, config_path: str | None) -> int:
  """Probe ``input_path`` and print the FFmpeg command that would run.

  Delegates to ``manual.py -i <file> -oo`` which is the canonical
  options-only preview — it loads the full settings stack, probes the
  source, runs generateOptions, and emits the assembled ffmpeg command
  to stdout. No new code path; no risk of drifting from production.
  """
  import subprocess

  input_file = Path(input_path)
  if not input_file.exists():
    sys.stderr.write(f"error: input file not found: {input_path}\n")
    return 1
  cmd = [sys.executable, str(ROOT / "manual.py"), "-i", str(input_file), "-oo", "-a"]
  if profile:
    cmd.extend(["-p", profile])
  if config_path and config_path not in (None, "synthesize"):
    cmd.extend(["-c", config_path])
  try:
    completed = subprocess.run(cmd, cwd=str(ROOT), check=False)
    return completed.returncode
  except FileNotFoundError as exc:
    sys.stderr.write(f"error invoking manual.py: {exc}\n")
    return 1


def main() -> int:
  args = _parse_args()
  if args.config is None:
    args.config, source_label = _default_source()
  else:
    source_label = args.config

  if args.input:
    if not Path(args.input).exists():
      sys.stderr.write(f"error: input file not found: {args.input}\n")
      return 1
    sys.stdout.write(f"# source: {source_label}\n")
    sys.stdout.write(f"# input:  {args.input}\n")
    sys.stdout.write(f"# profile: {args.profile or '(none)'}\n")
    sys.stdout.write("# generating FFmpeg command via manual.py -oo (no transcode performed)\n")
    sys.stdout.write("# " + "-" * 70 + "\n")
    sys.stdout.flush()
    return _render_ffmpeg_preview(args.input, args.profile, args.config)

  cfg = _load(args.config)

  if args.diff and args.profile is None:
    sys.stderr.write("error: --diff requires --profile\n")
    return 1

  if args.profile and args.profile not in cfg.profiles:
    sys.stderr.write(
      f"error: unknown profile '{args.profile}' (available: {sorted(cfg.profiles)})\n",
    )
    return 1

  if args.diff:
    base_raw = _resolve(cfg, None)
    resolved = _resolve(cfg, args.profile)
    data = _diff(base_raw, resolved)
    header = f"# source: {source_label}\n# diff: base vs profile '{args.profile}' (only fields the overlay changes)\n"
  else:
    data = _resolve(cfg, args.profile)
    header = f"# source: {source_label}\n# resolved config: profile={args.profile or '(none, raw base)'}\n"

  data = _filter_section(data, args.section)

  if args.format == "yaml":
    sys.stdout.write(header)
  _emit(data, args.format)
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
